[project]
name = "bank-statements"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "alai04", email = "alai04@gmail.com" }
]
requires-python = ">=3.10"
dependencies = [
    "pymupdf>=1.28.2",
]

[project.scripts]
bank-statements = "bank_statements:main"

[build-system]
requires = ["hatchling>=1.25"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/bank_statements"]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
